services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      # Set your database credentials here
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: default
      MYSQL_PASSWORD: ${USER_PASSWORD}
    ports:
      # Maps [Host Port]:[Container Port]
      - "3306:3306"
    volumes:
      # Ensures your data isn't deleted when the container stops
      - mysql_data:/var/lib/mysql
    healthcheck:
      # Official MySQL healthcheck
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
      
  opinehere.identity:
    build:
      context: .
      dockerfile: OpineHere.Identity/Dockerfile
    container_name: opineIdentity
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql_db;Port=3306;Database=${DB_NAME};Uid=default;Pwd=${USER_PASSWORD};"
      DefaultUserPassword: ${USER_PASSWORD}
      dockerfile: OpineHere.Identity/Dockerfile
    ports:
      - "5100:8080"
    expose:
      - "5100"
    #http://localhost:5100/api/Identity/me
    
  opinehere:
      build:
        context: .
        dockerfile: OpineHere.mvc/Dockerfile
      container_name: opinemvc
      depends_on:
        db:
          condition: service_healthy
      environment:
        ConnectionStrings__DefaultConnection: "Server=mysql_db;Port=3306;Database=${DB_NAME};Uid=default;Pwd=${USER_PASSWORD};"
        DefaultUserPassword: ${USER_PASSWORD}
        ASPNETCORE_ENVIRONMENT: Docker
        dockerfile: OpineHere.mvc/Dockerfile
      ports:
        - "5001:8080"
      #http://localhost:5001/
volumes:
  mysql_data:
