//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpineHere.mvc.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpineHere.mvc.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DefaultAppTitle {
            get {
                return ResourceManager.GetString("DefaultAppTitle", resourceCulture);
            }
        }
        
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        internal static string Bulletin {
            get {
                return ResourceManager.GetString("Bulletin", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string MakePost {
            get {
                return ResourceManager.GetString("MakePost", resourceCulture);
            }
        }
        
        internal static string PasetoSchemeName {
            get {
                return ResourceManager.GetString("PasetoSchemeName", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string PublishPost {
            get {
                return ResourceManager.GetString("PublishPost", resourceCulture);
            }
        }
        
        internal static string MarkdownSupportLabel {
            get {
                return ResourceManager.GetString("MarkdownSupportLabel", resourceCulture);
            }
        }
        
        internal static string DraftPost {
            get {
                return ResourceManager.GetString("DraftPost", resourceCulture);
            }
        }
        
        internal static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        internal static string WriteThoughts {
            get {
                return ResourceManager.GetString("WriteThoughts", resourceCulture);
            }
        }
    }
}
